name: Bug Report
description: Report a reproducible bug in sarzamin
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for reporting a bug in sarzamin!**
        Please fill in the following to help us reproduce and fix the issue.
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of sarzamin are you using?
      placeholder: e.g. 0.3.2
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and how to reproduce it.
      placeholder: A bug happened when I tried getting city name...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: What should have happened instead?
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: A minimal reproducible code or steps.
      placeholder: |
        1.`let yazd_cities = get_cities_of_province(121);`
        2. ...
  - type: textarea
    id: logs
    attributes:
      label: Logs or relevant output
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow the Code of Conduct
          required: true
