name: Bug Report
description: Report a reproducible bug in sarzamin
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report

        Thanks for reporting a bug in **sarzamin**!
        Please provide the following information to help us reproduce and fix the issue.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of sarzamin are you using?
      placeholder: e.g. 0.3.2
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug clearly and concisely.
      placeholder: |
        A bug happened when I tried getting city name from Yazd...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: Describe what you expected instead.
      placeholder: |
        I expected get_city_by_id(123) to return "Yazd", but it returned null.

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Provide a minimal code sample or detailed steps to reproduce.
      placeholder: |
        1. Call `get_cities_of_province(21)`
        2. Observe the returned list is empty
        3. ...

  - type: textarea
    id: logs
    attributes:
      label: Logs or Error Output
      description: Paste any error messages or logs here.
      render: shell
      placeholder: |
        thread 'main' panicked at 'index out of bounds', src/lib.rs:42

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow the [Code of Conduct](https://github.com/parsicore/sarzamin/blob/main/CODE_OF_CONDUCT.md)
          required: true
