blank_issues_enabled: false

contact_links:
  - name: 💬 Ask a question or discuss
    url: https://github.com/parsicore/sarzamin/discussions
    about: Use GitHub Discussions to ask questions or chat with the community.

  - name: 📄 Read the contributing guide
    url: https://github.com/parsicore/sarzamin/blob/main/CONTRIBUTING.md
    about: Learn how to report bugs and contribute to sarzamin.

  - name: 📖 Read the documentation
    url: https://docs.rs/sarzamin/
    about: Read the documentation for sarzamin.

  - name: 📜 Read the changelog
    url: https://github.com/parsicore/sarzamin/blob/main/CHANGELOG.md
    about: Stay up to date with new features and bug fixes.
