name: Refactor Request
description: Propose a code refactor or improvement
title: "[Refactor]: "
labels: ["refactor", "tech-debt"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **Think the code could be better? Let's talk refactor!**
  - type: textarea
    id: what
    attributes:
      label: What needs refactoring?
      placeholder: The name parsing logic is too complex...
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Why should this be refactored?
  - type: textarea
    id: suggestion
    attributes:
      label: How could it be improved?
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow the Code of Conduct
          required: true
